CREATE TABLE integration_readiness (
  id INT NOT NULL AUTO_INCREMENT,
  provider ENUM('iiko', 'premiumbonus') COLLATE utf8mb4_unicode_ci NOT NULL,
  module ENUM('menu', 'stoplist', 'delivery_zones', 'modifiers', 'orders', 'clients', 'loyalty') COLLATE utf8mb4_unicode_ci NOT NULL,
  status ENUM('not_configured', 'needs_mapping', 'ready') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'not_configured',
  total_count INT NOT NULL DEFAULT 0,
  linked_count INT NOT NULL DEFAULT 0,
  unlinked_count INT NOT NULL DEFAULT 0,
  stats JSON DEFAULT NULL,
  policy JSON DEFAULT NULL,
  last_checked_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_integration_readiness_provider_module (provider, module),
  KEY idx_integration_readiness_status (status),
  KEY idx_integration_readiness_last_checked_at (last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE integration_mapping_candidates (
  id INT NOT NULL AUTO_INCREMENT,
  provider ENUM('iiko', 'premiumbonus') COLLATE utf8mb4_unicode_ci NOT NULL,
  module ENUM('menu', 'stoplist', 'delivery_zones', 'modifiers', 'orders', 'clients', 'loyalty') COLLATE utf8mb4_unicode_ci NOT NULL,
  entity_type ENUM('category', 'item', 'variant', 'modifier', 'stoplist_entity') COLLATE utf8mb4_unicode_ci NOT NULL,
  local_entity_type ENUM('category', 'item', 'variant', 'modifier', 'unknown') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  local_entity_id INT DEFAULT NULL,
  local_name VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  external_entity_id VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  external_context JSON DEFAULT NULL,
  external_payload JSON DEFAULT NULL,
  confidence DECIMAL(5,2) DEFAULT NULL,
  state ENUM('suggested', 'confirmed', 'rejected', 'ignored', 'requires_review') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'suggested',
  notes TEXT COLLATE utf8mb4_unicode_ci,
  resolved_by INT DEFAULT NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_integration_mapping_candidates_lookup (provider, module, state),
  KEY idx_integration_mapping_candidates_local (local_entity_type, local_entity_id),
  KEY idx_integration_mapping_candidates_external (external_entity_id),
  KEY idx_integration_mapping_candidates_entity (entity_type),
  CONSTRAINT integration_mapping_candidates_ibfk_1 FOREIGN KEY (resolved_by) REFERENCES admin_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
