CREATE TABLE loyalty_bulk_accruals (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  status ENUM('draft', 'processing', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'draft',
  segment_config JSON NOT NULL,
  bonus_amount INT NOT NULL,
  message_template TEXT NULL,
  audience_count INT NOT NULL DEFAULT 0,
  success_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  skipped_count INT NOT NULL DEFAULT 0,
  requested_total_amount INT NOT NULL DEFAULT 0,
  actual_total_amount INT NOT NULL DEFAULT 0,
  created_by INT NOT NULL,
  started_at TIMESTAMP NULL DEFAULT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_loyalty_bulk_accruals_status (status),
  KEY idx_loyalty_bulk_accruals_created_by (created_by),
  KEY idx_loyalty_bulk_accruals_created_at (created_at),
  CONSTRAINT loyalty_bulk_accruals_ibfk_1 FOREIGN KEY (created_by) REFERENCES admin_users (id) ON DELETE RESTRICT,
  CONSTRAINT chk_loyalty_bulk_accruals_bonus_amount CHECK (bonus_amount > 0)
);

CREATE TABLE loyalty_bulk_accrual_recipients (
  id INT NOT NULL AUTO_INCREMENT,
  accrual_id INT NOT NULL,
  user_id INT NOT NULL,
  status ENUM('pending', 'completed', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
  error_message TEXT NULL,
  transaction_id INT NULL,
  notification_status ENUM('pending', 'sent', 'failed', 'skipped') NOT NULL DEFAULT 'skipped',
  notification_error TEXT NULL,
  processed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_loyalty_bulk_accrual_user (accrual_id, user_id),
  KEY idx_loyalty_bulk_recipients_status (status),
  KEY idx_loyalty_bulk_recipients_user (user_id),
  KEY idx_loyalty_bulk_recipients_processed_at (processed_at),
  CONSTRAINT loyalty_bulk_accrual_recipients_ibfk_1 FOREIGN KEY (accrual_id) REFERENCES loyalty_bulk_accruals (id) ON DELETE CASCADE,
  CONSTRAINT loyalty_bulk_accrual_recipients_ibfk_2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT loyalty_bulk_accrual_recipients_ibfk_3 FOREIGN KEY (transaction_id) REFERENCES loyalty_transactions (id) ON DELETE SET NULL
);
