-- Вынос настроек лояльности из system_settings
CREATE TABLE IF NOT EXISTS loyalty_settings (
  id INT PRIMARY KEY,
  bonus_max_redeem_percent DECIMAL(6, 4) NOT NULL DEFAULT 0.3,
  loyalty_level_1_name VARCHAR(50) NOT NULL DEFAULT 'Бронза',
  loyalty_level_2_name VARCHAR(50) NOT NULL DEFAULT 'Серебро',
  loyalty_level_3_name VARCHAR(50) NOT NULL DEFAULT 'Золото',
  loyalty_level_1_rate DECIMAL(6, 4) NOT NULL DEFAULT 0.03,
  loyalty_level_2_rate DECIMAL(6, 4) NOT NULL DEFAULT 0.05,
  loyalty_level_3_rate DECIMAL(6, 4) NOT NULL DEFAULT 0.07,
  loyalty_level_1_redeem_percent DECIMAL(6, 4) NOT NULL DEFAULT 0.3,
  loyalty_level_2_redeem_percent DECIMAL(6, 4) NOT NULL DEFAULT 0.3,
  loyalty_level_3_redeem_percent DECIMAL(6, 4) NOT NULL DEFAULT 0.3,
  loyalty_level_2_threshold INT NOT NULL DEFAULT 10000,
  loyalty_level_3_threshold INT NOT NULL DEFAULT 20000,
  include_delivery_in_earn BOOLEAN NOT NULL DEFAULT FALSE,
  calculate_from_amount_after_bonus BOOLEAN NOT NULL DEFAULT TRUE,
  level_calculation_period_days INT NOT NULL DEFAULT 60,
  level_calculation_include_delivery BOOLEAN NOT NULL DEFAULT FALSE,
  level_degradation_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  level_degradation_period_days INT NOT NULL DEFAULT 180,
  registration_bonus_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  registration_bonus_amount INT NOT NULL DEFAULT 1000,
  registration_bonus_expires_days INT NOT NULL DEFAULT 30,
  birthday_bonus_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  birthday_bonus_amount INT NOT NULL DEFAULT 500,
  birthday_bonus_days_before INT NOT NULL DEFAULT 3,
  birthday_bonus_days_after INT NOT NULL DEFAULT 7,
  default_bonus_expires_days INT NOT NULL DEFAULT 60,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO loyalty_settings (
  id,
  bonus_max_redeem_percent,
  loyalty_level_1_name,
  loyalty_level_2_name,
  loyalty_level_3_name,
  loyalty_level_1_rate,
  loyalty_level_2_rate,
  loyalty_level_3_rate,
  loyalty_level_1_redeem_percent,
  loyalty_level_2_redeem_percent,
  loyalty_level_3_redeem_percent,
  loyalty_level_2_threshold,
  loyalty_level_3_threshold,
  include_delivery_in_earn,
  calculate_from_amount_after_bonus,
  level_calculation_period_days,
  level_calculation_include_delivery,
  level_degradation_enabled,
  level_degradation_period_days,
  registration_bonus_enabled,
  registration_bonus_amount,
  registration_bonus_expires_days,
  birthday_bonus_enabled,
  birthday_bonus_amount,
  birthday_bonus_days_before,
  birthday_bonus_days_after,
  default_bonus_expires_days
) VALUES (
  1,
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'bonus_max_redeem_percent' LIMIT 1), 0.3),
  COALESCE((SELECT JSON_UNQUOTE(value) FROM system_settings WHERE `key` = 'loyalty_level_1_name' LIMIT 1), 'Бронза'),
  COALESCE((SELECT JSON_UNQUOTE(value) FROM system_settings WHERE `key` = 'loyalty_level_2_name' LIMIT 1), 'Серебро'),
  COALESCE((SELECT JSON_UNQUOTE(value) FROM system_settings WHERE `key` = 'loyalty_level_3_name' LIMIT 1), 'Золото'),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_1_rate' LIMIT 1), 0.03),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_2_rate' LIMIT 1), 0.05),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_3_rate' LIMIT 1), 0.07),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_1_redeem_percent' LIMIT 1), 0.3),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_2_redeem_percent' LIMIT 1), 0.3),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS DECIMAL(6,4)) FROM system_settings WHERE `key` = 'loyalty_level_3_redeem_percent' LIMIT 1), 0.3),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'loyalty_level_2_threshold' LIMIT 1), 10000),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'loyalty_level_3_threshold' LIMIT 1), 20000),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'include_delivery_in_earn' LIMIT 1), 0),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'calculate_from_amount_after_bonus' LIMIT 1), 1),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'level_calculation_period_days' LIMIT 1), 60),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'level_calculation_include_delivery' LIMIT 1), 0),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'level_degradation_enabled' LIMIT 1), 1),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'level_degradation_period_days' LIMIT 1), 180),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'registration_bonus_enabled' LIMIT 1), 1),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'registration_bonus_amount' LIMIT 1), 1000),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'registration_bonus_expires_days' LIMIT 1), 30),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'birthday_bonus_enabled' LIMIT 1), 1),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'birthday_bonus_amount' LIMIT 1), 500),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'birthday_bonus_days_before' LIMIT 1), 3),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'birthday_bonus_days_after' LIMIT 1), 7),
  COALESCE((SELECT CAST(JSON_UNQUOTE(value) AS UNSIGNED) FROM system_settings WHERE `key` = 'default_bonus_expires_days' LIMIT 1), 60)
) ON DUPLICATE KEY UPDATE
  bonus_max_redeem_percent = VALUES(bonus_max_redeem_percent),
  loyalty_level_1_name = VALUES(loyalty_level_1_name),
  loyalty_level_2_name = VALUES(loyalty_level_2_name),
  loyalty_level_3_name = VALUES(loyalty_level_3_name),
  loyalty_level_1_rate = VALUES(loyalty_level_1_rate),
  loyalty_level_2_rate = VALUES(loyalty_level_2_rate),
  loyalty_level_3_rate = VALUES(loyalty_level_3_rate),
  loyalty_level_1_redeem_percent = VALUES(loyalty_level_1_redeem_percent),
  loyalty_level_2_redeem_percent = VALUES(loyalty_level_2_redeem_percent),
  loyalty_level_3_redeem_percent = VALUES(loyalty_level_3_redeem_percent),
  loyalty_level_2_threshold = VALUES(loyalty_level_2_threshold),
  loyalty_level_3_threshold = VALUES(loyalty_level_3_threshold),
  include_delivery_in_earn = VALUES(include_delivery_in_earn),
  calculate_from_amount_after_bonus = VALUES(calculate_from_amount_after_bonus),
  level_calculation_period_days = VALUES(level_calculation_period_days),
  level_calculation_include_delivery = VALUES(level_calculation_include_delivery),
  level_degradation_enabled = VALUES(level_degradation_enabled),
  level_degradation_period_days = VALUES(level_degradation_period_days),
  registration_bonus_enabled = VALUES(registration_bonus_enabled),
  registration_bonus_amount = VALUES(registration_bonus_amount),
  registration_bonus_expires_days = VALUES(registration_bonus_expires_days),
  birthday_bonus_enabled = VALUES(birthday_bonus_enabled),
  birthday_bonus_amount = VALUES(birthday_bonus_amount),
  birthday_bonus_days_before = VALUES(birthday_bonus_days_before),
  birthday_bonus_days_after = VALUES(birthday_bonus_days_after),
  default_bonus_expires_days = VALUES(default_bonus_expires_days);

DELETE FROM system_settings
WHERE `key` IN (
  'loyalty_level_1_name',
  'loyalty_level_2_name',
  'loyalty_level_3_name',
  'bonus_max_redeem_percent',
  'loyalty_level_1_redeem_percent',
  'loyalty_level_2_redeem_percent',
  'loyalty_level_3_redeem_percent',
  'loyalty_level_1_rate',
  'loyalty_level_2_rate',
  'loyalty_level_3_rate',
  'loyalty_level_2_threshold',
  'loyalty_level_3_threshold',
  'include_delivery_in_earn',
  'calculate_from_amount_after_bonus',
  'level_calculation_period_days',
  'level_calculation_include_delivery',
  'level_degradation_enabled',
  'level_degradation_period_days',
  'registration_bonus_enabled',
  'registration_bonus_amount',
  'registration_bonus_expires_days',
  'birthday_bonus_enabled',
  'birthday_bonus_amount',
  'birthday_bonus_days_before',
  'birthday_bonus_days_after',
  'default_bonus_expires_days'
);
