export const broadcastsRoutes = [
  {
    path: "broadcasts",
    name: "broadcasts",
    component: () => import("@/modules/broadcasts/views/Broadcasts.vue"),
    meta: {
      title: "Рассылки",
      subtitle: "Маркетинговые кампании",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }],
      isList: true,
      listName: "broadcasts",
    },
  },
  {
    path: "broadcasts/new",
    name: "broadcast-new",
    component: () => import("@/modules/broadcasts/views/BroadcastForm.vue"),
    meta: {
      title: "Новая рассылка",
      subtitle: "Создание кампании",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }, { label: "Новая рассылка" }],
      isEdit: true,
      parentList: "broadcasts",
    },
  },
  {
    path: "broadcasts/:id/edit",
    name: "broadcast-edit",
    component: () => import("@/modules/broadcasts/views/BroadcastForm.vue"),
    meta: {
      title: "Редактирование рассылки",
      subtitle: "Настройка кампании",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }, { label: "Редактирование" }],
      isEdit: true,
      parentList: "broadcasts",
    },
  },
  {
    path: "broadcasts/segments",
    name: "broadcast-segments",
    component: () => import("@/modules/broadcasts/views/BroadcastSegments.vue"),
    meta: {
      title: "Сегменты",
      subtitle: "Сохраненные аудитории",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }, { label: "Сегменты" }],
      isList: true,
      listName: "broadcast-segments",
    },
  },
  {
    path: "broadcasts/dashboard",
    name: "broadcast-dashboard",
    component: () => import("@/modules/broadcasts/views/BroadcastDashboard.vue"),
    meta: {
      title: "Дашборд рассылок",
      subtitle: "Сводная аналитика",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }, { label: "Дашборд" }],
    },
  },
  {
    path: "broadcasts/:id",
    name: "broadcast-detail",
    component: () => import("@/modules/broadcasts/views/BroadcastDetail.vue"),
    meta: {
      title: "Статистика рассылки",
      subtitle: "Детальный отчет",
      permissions: ["marketing.broadcasts.manage"],
      breadcrumbs: [{ label: "Рассылки", to: "/broadcasts" }, { label: "Статистика" }],
      isDetail: true,
      parentList: "broadcasts",
    },
  },
  {
    path: "campaign",
    name: "subscription-campaigns",
    component: () => import("@/modules/subscription-campaigns/views/SubscriptionCampaigns.vue"),
    meta: {
      title: "Кампании подписки",
      subtitle: "Привлечение подписчиков",
      permissions: ["marketing.campaigns.manage"],
      breadcrumbs: [{ label: "Кампании подписки", to: "/campaign" }],
      isList: true,
      listName: "campaign",
    },
  },
  {
    path: "campaign/new",
    name: "subscription-campaign-new",
    component: () => import("@/modules/subscription-campaigns/views/SubscriptionCampaignForm.vue"),
    meta: {
      title: "Новая кампания подписки",
      subtitle: "Создание кампании",
      permissions: ["marketing.campaigns.manage"],
      breadcrumbs: [{ label: "Кампании подписки", to: "/campaign" }, { label: "Новая кампания" }],
      isEdit: true,
      parentList: "campaign",
    },
  },
  {
    path: "campaign/:id/edit",
    name: "subscription-campaign-edit",
    component: () => import("@/modules/subscription-campaigns/views/SubscriptionCampaignForm.vue"),
    meta: {
      title: "Редактирование кампании подписки",
      subtitle: "Настройка кампании",
      permissions: ["marketing.campaigns.manage"],
      breadcrumbs: [{ label: "Кампании подписки", to: "/campaign" }, { label: "Редактирование" }],
      isEdit: true,
      parentList: "campaign",
    },
  },
  {
    path: "campaign/:id",
    name: "subscription-campaign-detail",
    component: () =>
      import("@/modules/subscription-campaigns/views/SubscriptionCampaignDetail.vue"),
    meta: {
      title: "Статистика кампании подписки",
      subtitle: "Участники и конверсия",
      permissions: ["marketing.campaigns.manage"],
      breadcrumbs: [{ label: "Кампании подписки", to: "/campaign" }, { label: "Статистика" }],
      isDetail: true,
      parentList: "campaign",
    },
  },
];
