export const settingsRoutes = [
  {
    path: "cities",
    name: "cities",
    component: () => import("@/modules/delivery/views/Cities.vue"),
    meta: {
      title: "Города",
      subtitle: "Управление городами доставки",
      permissions: ["locations.cities.manage"],
      isList: true,
      listName: "cities",
    },
  },
  {
    path: "cities/new",
    name: "city-new",
    component: () => import("@/modules/delivery/views/CityForm.vue"),
    meta: {
      title: "Новый город",
      subtitle: "Создание города",
      permissions: ["locations.cities.manage"],
      breadcrumbs: [{ label: "Города", to: "/cities" }, { label: "Новый город" }],
      isEdit: true,
      parentList: "cities",
    },
  },
  {
    path: "cities/:id",
    name: "city-edit",
    component: () => import("@/modules/delivery/views/CityForm.vue"),
    meta: {
      title: "Редактирование города",
      subtitle: "Изменение города",
      permissions: ["locations.cities.manage"],
      breadcrumbs: [{ label: "Города", to: "/cities" }, { label: "Редактирование" }],
      isEdit: true,
      parentList: "cities",
    },
  },
  {
    path: "branches",
    name: "branches",
    component: () => import("@/modules/delivery/views/Branches.vue"),
    meta: {
      title: "Филиалы",
      subtitle: "Рестораны и точки самовывоза",
      permissions: ["locations.branches.view", "locations.branches.manage"],
      isList: true,
      listName: "branches",
    },
  },
  {
    path: "branches/new",
    name: "branch-new",
    component: () => import("@/modules/delivery/views/BranchForm.vue"),
    meta: {
      title: "Новый филиал",
      subtitle: "Создание филиала",
      permissions: ["locations.branches.manage"],
      breadcrumbs: [{ label: "Филиалы", to: "/branches" }, { label: "Новый филиал" }],
      isEdit: true,
      parentList: "branches",
    },
  },
  {
    path: "branches/:id",
    name: "branch-edit",
    component: () => import("@/modules/delivery/views/BranchForm.vue"),
    meta: {
      title: "Редактирование филиала",
      subtitle: "Изменение филиала",
      permissions: ["locations.branches.manage"],
      breadcrumbs: [{ label: "Филиалы", to: "/branches" }, { label: "Редактирование" }],
      isEdit: true,
      parentList: "branches",
    },
  },
  {
    path: "delivery-zones",
    name: "delivery-zones",
    component: () => import("@/modules/delivery/views/DeliveryZones.vue"),
    meta: {
      title: "Зоны доставки",
      subtitle: "Полигоны на карте",
      sidebarCollapsed: true,
      fullBleed: true,
      permissions: ["locations.delivery_zones.view", "locations.delivery_zones.manage"],
      isList: true,
      listName: "delivery-zones",
    },
  },
  {
    path: "delivery-zones/:branchId/:polygonId",
    name: "delivery-zone-editor",
    component: () => import("@/modules/delivery/views/DeliveryZoneEditor.vue"),
    meta: {
      title: "Полигон доставки",
      subtitle: "Редактирование зоны",
      sidebarCollapsed: true,
      fullBleed: true,
      permissions: ["locations.delivery_zones.manage"],
      isEdit: true,
      parentList: "delivery-zones",
    },
  },
  {
    path: "system/settings",
    name: "system-settings",
    component: () => import("@/modules/system/views/SystemSettings.vue"),
    meta: {
      title: "Настройки системы",
      subtitle: "Модули и функциональные блоки",
      permissions: ["system.settings.manage"],
    },
  },
  {
    path: "integrations",
    name: "integrations",
    component: () => import("@/modules/system/views/IntegrationsSettings.vue"),
    meta: {
      title: "Интеграции",
      subtitle: "iiko и PremiumBonus",
      permissions: ["system.integrations.manage"],
    },
  },
];
