import { createApp } from "vue";
import { createPinia } from "pinia";
import router from "./router/index.js";
import "./style.css";
import "vue-sonner/style.css";
import App from "./App.vue";
import { useAuthStore } from "@/shared/stores/auth.js";
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
const authStore = useAuthStore(pinia);
authStore.initCrossTabSync();
app.use(router);
app.mount("#app");
